version: "3.8"
services:
  service:
    container_name: schebule-service
    build: .
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://schebule-db:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRESDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
    depends_on:
      - postgres

  postgres:
    container_name: schebule-db
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    volumes:
      - postgres:/data/postgres
      - ./docker/db-init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  postgres:
    driver: local
